//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ToursansTripArange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int Id { get; set; }
         [Required]
        public string Name { get; set; }
         [Required]
        public string Phonenumber { get; set; }
         [Required]
        public string Email { get; set; }
         [Required]
        public string Address { get; set; }
        [Required]
        [MaxLength(13), MinLength(13)]
        public string Cinc { get; set; }
         [Required]
        public string Noofpeoples { get; set; }
         [Required]
        public string place { get; set; }
         [Required]
        public string Daysfortrip { get; set; }
         [Required]
        public string Hoteltostay { get; set; }
    }
}
