//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ToursansTripArange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public int Id { get; set; }
         [Required]
        public string name { get; set; }
         [Required]
        public string email { get; set; }
         [Required]
        public string phonenumber { get; set; }
         [Required]
        public string address { get; set; }
        [Required]
        [MaxLength(13), MinLength(13)]
        public string cnic { get; set; }
    }
}
