//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ToursansTripArange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int Id { get; set; }
         [Required]
        public string placename { get; set; }
         [Required]
        public string placelocation { get; set; }
         [Required]
        public string placedescription { get; set; }
         [Required]
        public string placeimage { get; set; }
    }
}
